import Head from 'next/head'
import { PageContainer } from '@/components/PageContainer'
import Header from '@/components/inc/Header'
import Highlight from 'react-highlight'
import Link from 'next/link'

export default function Home() {
  return (
    <div>
      <Head>
        <title>What's new in Laravel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={'h-full dark:bg-zinc-800'}>
        <PageContainer>
          <div className={'flex flex-col'}>
            <Header />
            <main>
              <Highlight className="php my-8 mx-auto max-w-5xl rounded-2xl">
                {`
      use Illuminate\\Support\\Facades\\File;

      if (File::isDirectoryEmpty('john/photos')) {
          return 'You do not have any photos';
      }

      if (File::isDirectoryNotEmpty('john/videos', true)) {
          return 'You may have one or more videos, even hidden ones.';
  }
                  `}
              </Highlight>
            </main>
          </div>
        </PageContainer>
      </div>
    </div>
  )
}
